drop table DM_EXTRA_PREM;
create table DM_EXTRA_PREM(
LIST_ID                        varchar2(300)  primary key,
ITEM_ID                        varchar2(300) ,
EXTRA_TYPE                     varchar2(300) ,
START_DATE                     varchar2(300) ,
END_DATE                       varchar2(300) ,
POLICY_ID                      varchar2(300) ,
EXTRA_ARITH                    varchar2(300) ,
EXTRA_PREM                     varchar2(300) ,
EXTRA_PARA                     varchar2(300) ,
NEXT_EXTRA_PREM                varchar2(300) ,
EM_VALUE                       varchar2(300) ,
REASON                         varchar2(4000) ,
INSURED_ID                     varchar2(300) ,
EXTRA_STATUS                   varchar2(300) ,
RE_CALC_INDI                   varchar2(300) ,
EXTRA_PREM_AN                  varchar2(300) ,
NEXT_EXTRA_PREM_AN             varchar2(300) 
);
drop table DM_CONTRACT_BENE;
create table DM_CONTRACT_BENE(
LIST_ID                        varchar2(300)  primary key,
PARTY_ID                       varchar2(300) ,
POLICY_ID                      varchar2(300) ,
INSURANT                       varchar2(300) ,
BENE_TYPE                      varchar2(300) ,
SHARE_ORDER                    varchar2(300) ,
SHARE_RATE                     varchar2(300) ,
DESIGNATION                    varchar2(300) ,
LEGAL_BENE                     varchar2(300) ,
ADDRESS_ID                     varchar2(300) ,
IRREVOCABLE_INDI               varchar2(300) 
);
drop table DM_CONTRACT_MASTER;
create table DM_CONTRACT_MASTER(
POLICY_ID                      varchar2(300)  primary key,
POLICY_CODE                    varchar2(300) ,
APPLY_CODE                     varchar2(300) ,
ORGAN_ID                       varchar2(300) ,
MONEY_ID                       varchar2(300) ,
SUBMIT_CHANNEL                 varchar2(300) ,
ASSIGNMENT_TYPE                varchar2(300) ,
ASSIGNMENT_ID                  varchar2(300) ,
PROPOSAL_STATUS                varchar2(300) ,
COMMENTS                       varchar2(1000) ,
APPLICANT_AGE                  varchar2(300) ,
PARTY_ID                       varchar2(300) ,
BIRTH_DATE                     varchar2(300) ,
JOB_CLASS                      varchar2(300) ,
ADDRESS_ID                     varchar2(300) ,
JOB_CATE_ID                    varchar2(300) ,
PARTY_ID_PAYER                 varchar2(300) ,
PAY_MODE                       varchar2(300) ,
ACCOUNT_ID                     varchar2(300) ,
PAY_MONEY_ID                   varchar2(300) ,
PRECONT_TIME                   varchar2(300) ,
CONVERSION_AGE                 varchar2(300) ,
CHANNEL_TYPE                   varchar2(300) ,
TOTAL_PAID_PREM                varchar2(300) ,
REMARK                         varchar2(300) ,
ADDRESS_ID_PAYER               varchar2(300) ,
LANG_ID                        varchar2(300) 
);
drop table DM_PREM_DISCNT;
create table DM_PREM_DISCNT(
DISCNT_ID                      varchar2(300)  primary key,
ITEM_ID                        varchar2(300) ,
DISCNT_SOURCE                  varchar2(300) ,
DISCOUNT_TYPE                  varchar2(300) ,
DISCNT_RATE                    varchar2(300) ,
DISCNT_PREM_AF                 varchar2(300) ,
DISCNT_PREM_AN                 varchar2(300) ,
NEXT_DISCNT_RATE               varchar2(300) ,
NEXT_DISCNT_PREM_AF            varchar2(300) ,
NEXT_DISCNT_PREM_AN            varchar2(300) ,
POLICY_ID                      varchar2(300) 
);
drop table DM_SUSPENSE;
create table DM_SUSPENSE(
POLICY_CODE                    varchar2(300) ,
APPLY_CODE                     varchar2(300) ,
CERTI_TYPE                     varchar2(300) ,
CERTI_CODE                     varchar2(300) ,
SUSPENSE_TYPE                  varchar2(300) ,
SUSP_AMT                       varchar2(300) ,
SUSP_DATE                      varchar2(300) 
);
drop table DM_CONTRACT_PRODUCT;
create table DM_CONTRACT_PRODUCT(
ITEM_ID                        varchar2(300)  primary key,
MASTER_ID                      varchar2(300) ,
POLICY_ID                      varchar2(300) ,
PRODUCT_ID                     varchar2(300) ,
AMOUNT                         varchar2(300) ,
UNIT                           varchar2(300) ,
APPLY_DATE                     varchar2(300) ,
EXPIRY_DATE                    varchar2(300) ,
VALIDATE_DATE                  varchar2(300) ,
PAIDUP_DATE                    varchar2(300) ,
LIABILITY_STATE                varchar2(300) ,
END_CAUSE                      varchar2(300) ,
RENEWAL_TYPE                   varchar2(300) ,
CHARGE_PERIOD                  varchar2(300) ,
CHARGE_YEAR                    varchar2(300) ,
COVERAGE_PERIOD                varchar2(300) ,
COVERAGE_YEAR                  varchar2(300) ,
BENEFIT_LEVEL                  varchar2(300) ,
INSURED_CATEGORY               varchar2(300) ,
DECISION_ID                    varchar2(300) ,
COUNT_WAY                      varchar2(300) ,
RENEW_DECISION                 varchar2(300) ,
BONUS_SA                       varchar2(300) ,
ORIGIN_SA                      varchar2(300) ,
ORIGIN_BONUS_SA                varchar2(300) ,
WAIVER_START                   varchar2(300) ,
WAIVER_END                     varchar2(300) ,
STD_PREM_AF                    varchar2(300) ,
DISCNT_PREM_AF                 varchar2(300) ,
POLICY_FEE_AF                  varchar2(300) ,
EXTRA_PREM_AF                  varchar2(300) ,
TOTAL_PREM_AF                  varchar2(300) ,
STD_PREM_AN                    varchar2(300) ,
DISCNT_PREM_AN                 varchar2(300) ,
POLICY_FEE_AN                  varchar2(300) ,
EXTRA_PREM_AN                  varchar2(300) ,
NEXT_STD_PREM_AF               varchar2(300) ,
NEXT_DISCNT_PREM_AF            varchar2(300) ,
NEXT_POLICY_FEE_AF             varchar2(300) ,
NEXT_EXTRA_PREM_AF             varchar2(300) ,
NEXT_TOTAL_PREM_AF             varchar2(300) ,
NEXT_STD_PREM_AN               varchar2(300) ,
NEXT_DISCNT_PREM_AN            varchar2(300) ,
NEXT_POLICY_FEE_AN             varchar2(300) ,
NEXT_EXTRA_PREM_AN             varchar2(300) ,
LAPSE_CAUSE                    varchar2(300) ,
SUBMISSION_DATE                varchar2(300) ,
ACTUAL_VALIDATE                varchar2(300) ,
INITIAL_VALI_DATE              varchar2(300) ,
ISSUE_DATE                     varchar2(300) ,
RISK_COMMENCE_DATE             varchar2(300) ,
DUE_DATE                       varchar2(300) ,
PREM_STATUS                    varchar2(300) ,
BILLING_DATE                   varchar2(300) ,
LAPSE_DATE                     varchar2(300) ,
END_DATE                       varchar2(300) ,
WAIVER_SA                      varchar2(300) ,
FLOATER_PLAN                   varchar2(300) 
);
drop table DM_POLICY_PRODUCER_ROLE;
create table DM_POLICY_PRODUCER_ROLE(
ROLE_ID                        varchar2(300)  primary key,
POLICY_ID                      varchar2(300) ,
ITEM_ID                        varchar2(300) ,
PRODUCER_ROLE                  varchar2(300) ,
PRODUCER_ID                    varchar2(300) ,
PRODUCER_POSITION              varchar2(300) ,
ASSIGN_RATE                    varchar2(300) ,
START_DATE                     varchar2(300) ,
END_DATE                       varchar2(300) ,
HIERARCHY_DATE                 varchar2(300) 
);
drop table DM_POLICY_EXCLUSION;
create table DM_POLICY_EXCLUSION(
EXCLUSION_ID                   varchar2(300)  primary key,
EXCLUSION_CODE                 varchar2(300) ,
POLICY_ID                      varchar2(300) ,
ITEM_ID                        varchar2(300) ,
DESC_LANG1                     varchar2(4000) ,
EFFECT_DATE                    varchar2(300) ,
EXPIRY_DATE                    varchar2(300) 
);
drop table DM_BENEFIT_INSURED;
create table DM_BENEFIT_INSURED(
LIST_ID                        varchar2(300)  primary key,
ITEM_ID                        varchar2(300) ,
PARTY_ID                       varchar2(300) ,
ENTRY_AGE                      varchar2(300) ,
POLICY_ID                      varchar2(300) ,
ORDER_ID                       varchar2(300) ,
JOB_CLASS                      varchar2(300) ,
MEDICAL_EXAM_INDI              varchar2(300) ,
ADDRESS_ID                     varchar2(300) ,
RELATION_TO_PH                 varchar2(300) ,
INSURED_STATUS                 varchar2(300) ,
BIRTH_DATE                     varchar2(300) ,
EM_VALUE                       varchar2(300) ,
GENDER                         varchar2(300) ,
JOB_CATE_ID                    varchar2(300) ,
SMOKING                        varchar2(300) ,
STAND_LIFE                     varchar2(300) 
);
